# sudo false implies containerized builds
sudo: false

language: python

python:
  - 3.6
#  - 3.7 # Travis does not have python 3.7 at the moment...

# env:
#   global:
#     # List package dependencies for conda
#     - CONDA_DEPS="pytest numpy scipy scikit-learn"
#     # package name for test invocation
#     - PACKAGENAME="run_test"

before_install:
# install miniconda
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda create -n testenv python=$TRAVIS_PYTHON_VERSION
- source activate testenv
# install prody
- conda install numpy
- pip install -U prody
# install dependencies for rhapsody
- conda install scipy scikit-learn
#- conda install -c conda-forge biopython
# or: conda install --yes pyparsing biopython


# install:
# - python setup.py install

script:
- cd test
#################### TO DO:
- pytest test1.py
